### PR TITLE
Connect with backend

### PR DESCRIPTION
**Pull request by anlhu**
connect sidebar, problem statement, goal statement with the backend api

### CODE REVIEW

**Comment by anlhu** [comment]
Release version is not in the database... We may need a new column for this and update all the db functions :/

**Comment by anlhu** [comment]
Text boxes are not editable either

**Comment by anlhu** [comment]
Also, this will probably need refactoring

**Comment by anlhu** [comment]
Can do more after we connect with the project select page

**Review by arthurrfoy — APPROVED** [review]

**Pull request merged**
